In [50]:
#! -*- coding: UTF8 -*-
import os
os.chdir(os.getcwd())

## Import Module

In [51]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [52]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

## Import Data 

In [53]:
df1 = pd.read_excel('process_data/GPP_6210501001.xlsx',sheet_name="LopBuri",index_col="Year") #ตัวอย่าง
df1.head()

Agriculture, forestry and fishing  Mining and quarrying  Manufacturing  \
Year                                                                           
1995                        5391.575854             19.009823    7176.043232   
1996                        6206.682558             37.744703    6810.317457   
1997                        6014.415215             36.238535    6988.106194   
1998                        6270.177149             28.193053    5739.574622   
1999                        5684.674097             42.046276    4594.756351   

      Electricity, gas, steam and air conditioning supply  \
Year                                                        
1995                                         590.238706     
1996                                         677.218307     
1997                                         817.941119     
1998                                        1090.869869     
1999                                         958.722269     

      Water supply; sewerage, waste management and remediation activities  \
Year                                                                        
1995                                         142.277622                     
1996                                         137.423999                     
1997                                         149.159330                     
1998                                         130.489143                     
1999                                         143.734495                     

      Construction  Wholesale and retail trade and repair of motor vehicles  \
Year                                                                          
1995   3391.005101                                        3484.507633         
1996   7728.645631                                        3737.141208         
1997   5647.894247                                        4542.778789         
1998   3182.288913                                        4987.801949         
1999   2304.876078                                        4652.336854         

      Transportation and storage  Accommodation and food service activities  \
Year                                                                          
1995                 1016.736730                                 176.898917   
1996                 1113.256820                                 153.858116   
1997                 1172.783861                                 140.141879   
1998                 1245.856126                                 474.662929   
1999                 1226.177795                                 564.896952   

      Information and communication  ...  \
Year                                 ...   
1995                     195.790885  ...   
1996                     224.369211  ...   
1997                     234.727143  ...   
1998                     229.726314  ...   
1999                     241.436570  ...   

      การนำเข้าสินค้าและบริการ (คิดเป็น % ของจีดีพี)  \
Year                                                   
1995                                       48.223830   
1996                                       45.255728   
1997                                       46.814732   
1998                                       42.303171   
1999                                       44.267746   

      มูลค่าเพิ่มของอุตสาหกรรม (คิดเป็น % ของจีดีพี)  \
Year                                                   
1995                                       37.278020   
1996                                       37.081286   
1997                                       36.564600   
1998                                       36.111727   
1999                                       36.378900   

      จำนวนประชากรทั้งหมด (คน)  \
Year                             
1995                  59467272   
1996                  60130190   
1997                  60846588   
1998                  61585103   
1999                  62298569   

      ค่าใช้จ่ายในการวิจัยและพัฒนา 

In [54]:
df1.keys()

Index(['Agriculture, forestry and fishing', 'Mining and quarrying',
       'Manufacturing', 'Electricity, gas, steam and air conditioning supply',
       'Water supply; sewerage, waste management and remediation activities',
       'Construction',
       'Wholesale and retail trade and repair of motor vehicles',
       'Transportation and storage',
       'Accommodation and food service activities',
       'Information and communication', 'Financial and insurance activities',
       'Real estate activities',
       'Professional, scientific and technical activities',
       'Administrative and support service activities',
       'Public administration and defence; compulsory social security',
       'Education', 'Human health activities',
       'Arts, entertainment and recreation', 'Other service activities',
       'การค้าสินค้า (คิดเป็น % ของจีดีพี)',
       'มูลค่าเพิ่มของการเกษตร (คิดเป็น % ของจีดีพี)',
       'การนำเข้าสินค้าและบริการ (คิดเป็น % ของจีดีพี)',
       'มูลค่าเพิ่มขอ

## Find data by Regression

##### รายจ่ายของประชากรในจังหวัดลพบุรี (บาท)

In [55]:
ex1 = df1.loc[[i for i in range(2006,2019)],['รายจ่ายของประชากรในจังหวัดลพบุรี (บาท)','GPP Per capita (Baht)']]
ex1

รายจ่ายของประชากรในจังหวัดลพบุรี (บาท)  GPP Per capita (Baht)
Year                                                               
2006                                15870.00             298954.253
2007                                14462.00             339993.396
2008                                15386.00             438555.445
2009                                16764.00             379657.777
2010                                14433.00             427733.436
2011                                14875.40             365800.945
2012                                17356.96             378620.537
2013                                15944.80             461789.496
2014                                14910.71             417614.341
2015                                17968.90             468325.834
2016                                15875.50             444803.565
2017                                16012.15             449602.967
2018                                17016.83             454952.541

In [56]:
import statsmodels.api as sm
X = ex1[['GPP Per capita (Baht)']]
X = sm.add_constant(X, prepend=False)
X.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
2006             298954.253    1.0
2007             339993.396    1.0
2008             438555.445    1.0
2009             379657.777    1.0
2010             427733.436    1.0

In [57]:
y = ex1['รายจ่ายของประชากรในจังหวัดลพบุรี (บาท)']
y.head()

Year
2006    15870.0
2007    14462.0
2008    15386.0
2009    16764.0
2010    14433.0
Name: รายจ่ายของประชากรในจังหวัดลพบุรี (บาท), dtype: float64

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05,random_state=14)  

In [59]:
lm = LinearRegression()
lm.fit(X_train, y_train)

LinearRegression()

In [60]:
X_train

GPP Per capita (Baht)  const
Year                              
2009             379657.777    1.0
2018             454952.541    1.0
2007             339993.396    1.0
2006             298954.253    1.0
2015             468325.834    1.0
2010             427733.436    1.0
2008             438555.445    1.0
2016             444803.565    1.0
2013             461789.496    1.0
2012             378620.537    1.0
2014             417614.341    1.0
2017             449602.967    1.0

In [61]:
test_ex1 = df1.loc[[i for i in range(1995,2006)],['GPP Per capita (Baht)']]
test_ex1

GPP Per capita (Baht)
Year                       
1995             143862.554
1996             171503.917
1997             179223.451
1998             180611.806
1999             189856.706
2000             219141.847
2001             219060.592
2002             231122.492
2003             256743.101
2004             271765.117
2005             273739.910

In [62]:
X_test_ex1 = test_ex1[['GPP Per capita (Baht)']]
X_test_ex1 = sm.add_constant(X_test_ex1, prepend=False)
X_test_ex1.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
1995             143862.554    1.0
1996             171503.917    1.0
1997             179223.451    1.0
1998             180611.806    1.0
1999             189856.706    1.0

In [63]:
predictions = lm.predict(X_test_ex1)
predictions                   

array([14642.05707269, 14781.33134225, 14820.22712533, 14827.22251585,
       14873.80403553, 15021.36067454, 15020.95126163, 15081.72656826,
       15210.81903032, 15286.50923075, 15296.45945834])

##### เนื้อที่ที่ถือครองเพื่อการเกษตร (ไร่)

In [64]:
ex2 = df1.loc[[i for i in range(2010,2019)],['เนื้อที่ที่ถือครองเพื่อการเกษตร (ไร่)','GPP Per capita (Baht)']]
ex2

เนื้อที่ที่ถือครองเพื่อการเกษตร (ไร่)  GPP Per capita (Baht)
Year                                                              
2010                              2541350.0             427733.436
2011                              2541569.0             365800.945
2012                              2196101.0             378620.537
2013                              2189464.0             461789.496
2014                              2211616.0             417614.341
2015                              2191974.0             468325.834
2016                              2191454.0             444803.565
2017                              2191311.0             449602.967
2018                              2191867.0             454952.541

In [65]:
X = ex2[['GPP Per capita (Baht)']]
X = sm.add_constant(X, prepend=False)
X.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
2010             427733.436    1.0
2011             365800.945    1.0
2012             378620.537    1.0
2013             461789.496    1.0
2014             417614.341    1.0

In [66]:
y = ex2['เนื้อที่ที่ถือครองเพื่อการเกษตร (ไร่)']
y.head()

Year
2010    2541350.0
2011    2541569.0
2012    2196101.0
2013    2189464.0
2014    2211616.0
Name: เนื้อที่ที่ถือครองเพื่อการเกษตร (ไร่), dtype: float64

In [67]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05,random_state=14)  

In [68]:
lm = LinearRegression()
lm.fit(X_train, y_train)

LinearRegression()

In [69]:
test_ex2 = df1.loc[[i for i in range(1995,2010)],['GPP Per capita (Baht)']]
test_ex2

GPP Per capita (Baht)
Year                       
1995             143862.554
1996             171503.917
1997             179223.451
1998             180611.806
1999             189856.706
2000             219141.847
2001             219060.592
2002             231122.492
2003             256743.101
2004             271765.117
2005             273739.910
2006             298954.253
2007             339993.396
2008             438555.445
2009             379657.777

In [70]:
X_test_ex2 = test_ex2[['GPP Per capita (Baht)']]
X_test_ex2 = sm.add_constant(X_test_ex2, prepend=False)
X_test_ex2.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
1995             143862.554    1.0
1996             171503.917    1.0
1997             179223.451    1.0
1998             180611.806    1.0
1999             189856.706    1.0

In [71]:
predictions = lm.predict(X_test_ex2)
predictions  

array([2918084.49750019, 2855554.76352968, 2838091.78938487,
       2834951.08070106, 2814037.45435116, 2747789.19893703,
       2747973.01235946, 2720686.82541641, 2662728.40039474,
       2628745.89872937, 2624278.5618279 , 2567239.18355878,
       2474401.26184821, 2251436.18217548, 2384673.29901096])

##### จำนวนโรงงานอุตสาหกรรม (โรงงาน)

In [72]:
ex3= df1.loc[[i for i in range(2011,2019)],['จำนวนโรงงานอุตสาหกรรม (โรงงาน)','GPP Per capita (Baht)']]
ex3

จำนวนโรงงานอุตสาหกรรม (โรงงาน)  GPP Per capita (Baht)
Year                                                       
2011                            26.0             365800.945
2012                            40.0             378620.537
2013                            32.0             461789.496
2014                            37.0             417614.341
2015                            59.0             468325.834
2016                            31.0             444803.565
2017                            19.0             449602.967
2018                            30.0             454952.541

In [73]:
X = ex3[['GPP Per capita (Baht)']]
X = sm.add_constant(X, prepend=False)
X.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
2011             365800.945    1.0
2012             378620.537    1.0
2013             461789.496    1.0
2014             417614.341    1.0
2015             468325.834    1.0

In [74]:
y = ex3['จำนวนโรงงานอุตสาหกรรม (โรงงาน)']
y.head()

Year
2011    26.0
2012    40.0
2013    32.0
2014    37.0
2015    59.0
Name: จำนวนโรงงานอุตสาหกรรม (โรงงาน), dtype: float64

In [75]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05,random_state=14)  

In [76]:
lm = LinearRegression()
lm.fit(X_train, y_train)

LinearRegression()

In [77]:
test_ex3 = df1.loc[[i for i in range(1995,2011)],['GPP Per capita (Baht)']]
test_ex3

GPP Per capita (Baht)
Year                       
1995             143862.554
1996             171503.917
1997             179223.451
1998             180611.806
1999             189856.706
2000             219141.847
2001             219060.592
2002             231122.492
2003             256743.101
2004             271765.117
2005             273739.910
2006             298954.253
2007             339993.396
2008             438555.445
2009             379657.777
2010             427733.436

In [78]:
X_test_ex3 = test_ex3[['GPP Per capita (Baht)']]
X_test_ex3 = sm.add_constant(X_test_ex3, prepend=False)
X_test_ex3.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
1995             143862.554    1.0
1996             171503.917    1.0
1997             179223.451    1.0
1998             180611.806    1.0
1999             189856.706    1.0

In [79]:
predictions = lm.predict(X_test_ex3)
predictions  

array([16.13101456, 17.938184  , 18.44288074, 18.53365024, 19.13807415,
       21.05271243, 21.04740004, 21.83599708, 23.51105129, 24.49317826,
       24.62228859, 26.27078146, 28.95388666, 35.39779184, 31.54711106,
       34.69025785])

##### เนื้อที่สำหรับปลูกพืชไร่ (ไร่)

In [80]:
ex4 = df1.loc[[i for i in range(2010,2019)],['เนื้อที่สำหรับปลูกพืชไร่ (ไร่)','GPP Per capita (Baht)']]
ex4

เนื้อที่สำหรับปลูกพืชไร่ (ไร่)  GPP Per capita (Baht)
Year                                                       
2010                       1149975.0             427733.436
2011                       1154555.0             365800.945
2012                       1153432.0             378620.537
2013                       1153662.0             461789.496
2014                       1154050.0             417614.341
2015                       1133959.0             468325.834
2016                       1133991.0             444803.565
2017                       1133430.0             449602.967
2018                       1134183.0             454952.541

In [81]:
X = ex4[['GPP Per capita (Baht)']]
X = sm.add_constant(X, prepend=False)
X.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
2010             427733.436    1.0
2011             365800.945    1.0
2012             378620.537    1.0
2013             461789.496    1.0
2014             417614.341    1.0

In [82]:
y = ex4['เนื้อที่สำหรับปลูกพืชไร่ (ไร่)']
y.head()

Year
2010    1149975.0
2011    1154555.0
2012    1153432.0
2013    1153662.0
2014    1154050.0
Name: เนื้อที่สำหรับปลูกพืชไร่ (ไร่), dtype: float64

In [83]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.001,random_state=14)

In [84]:
lm = LinearRegression()
lm.fit(X_train, y_train)

LinearRegression()

In [85]:
test_ex4 = df1.loc[[i for i in range(1995,2010)],['GPP Per capita (Baht)']]
test_ex4

GPP Per capita (Baht)
Year                       
1995             143862.554
1996             171503.917
1997             179223.451
1998             180611.806
1999             189856.706
2000             219141.847
2001             219060.592
2002             231122.492
2003             256743.101
2004             271765.117
2005             273739.910
2006             298954.253
2007             339993.396
2008             438555.445
2009             379657.777

In [86]:
X_test_ex4 = test_ex4[['GPP Per capita (Baht)']]
X_test_ex4 = sm.add_constant(X_test_ex4, prepend=False)
X_test_ex4.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
1995             143862.554    1.0
1996             171503.917    1.0
1997             179223.451    1.0
1998             180611.806    1.0
1999             189856.706    1.0

In [87]:
predictions = lm.predict(X_test_ex4)
predictions  

array([1193554.53085165, 1188872.01885004, 1187564.31160702,
       1187329.12099974, 1185763.01316332, 1180802.04129658,
       1180815.80608498, 1178772.49181309, 1174432.30029898,
       1171887.53540412, 1171553.00081828, 1167281.63172153,
       1160329.50422936, 1143632.8609652 , 1153610.26465825])

##### เนื้อที่สำหรับปลูกนาข้าว (ไร่)

In [88]:
ex5 = df1.loc[[i for i in range(2010,2019)],['เนื้อที่สำหรับปลูกนาข้าว (ไร่)','GPP Per capita (Baht)']]
ex5

เนื้อที่สำหรับปลูกนาข้าว (ไร่)  GPP Per capita (Baht)
Year                                                       
2010                        825214.0             427733.436
2011                        812779.0             365800.945
2012                        812975.0             378620.537
2013                        812719.0             461789.496
2014                        812522.0             417614.341
2015                        813100.0             468325.834
2016                        812485.0             444803.565
2017                        813167.0             449602.967
2018                        812834.0             454952.541

In [89]:
X = ex5[['GPP Per capita (Baht)']]
X = sm.add_constant(X, prepend=False)
X.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
2010             427733.436    1.0
2011             365800.945    1.0
2012             378620.537    1.0
2013             461789.496    1.0
2014             417614.341    1.0

In [90]:
y = ex5['เนื้อที่สำหรับปลูกนาข้าว (ไร่)']
y.head()

Year
2010    825214.0
2011    812779.0
2012    812975.0
2013    812719.0
2014    812522.0
Name: เนื้อที่สำหรับปลูกนาข้าว (ไร่), dtype: float64

In [91]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.000000000001,random_state=14)

In [92]:
lm = LinearRegression()
lm.fit(X_train, y_train)

LinearRegression()

In [93]:
test_ex5 = df1.loc[[i for i in range(1995,2010)],['GPP Per capita (Baht)']]
test_ex5

GPP Per capita (Baht)
Year                       
1995             143862.554
1996             171503.917
1997             179223.451
1998             180611.806
1999             189856.706
2000             219141.847
2001             219060.592
2002             231122.492
2003             256743.101
2004             271765.117
2005             273739.910
2006             298954.253
2007             339993.396
2008             438555.445
2009             379657.777

In [94]:
X_test_ex5 = test_ex5[['GPP Per capita (Baht)']]
X_test_ex5 = sm.add_constant(X_test_ex5, prepend=False)
X_test_ex5.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
1995             143862.554    1.0
1996             171503.917    1.0
1997             179223.451    1.0
1998             180611.806    1.0
1999             189856.706    1.0

In [95]:
predictions = lm.predict(X_test_ex5)
predictions  

array([813441.82643235, 813529.79148508, 813554.35790083, 813558.77616055,
       813588.19685576, 813681.39301879, 813681.13443529, 813719.51986764,
       813801.05413285, 813848.85975046, 813855.14427305, 813935.38564942,
       814065.98739934, 814379.64833703, 814192.2141475 ])

## Find data by Interpolation

In [96]:
ex6 = df1['ค่าใช้จ่ายในการวิจัยและพัฒนา (คิดเป็น % ของจีดีพี)']
ex6

Year
1995        NaN
1996    0.11918
1997    0.10214
1998        NaN
1999    0.24836
2000    0.24471
2001    0.25231
2002    0.23055
2003    0.24534
2004    0.23828
2005    0.21889
2006    0.23271
2007    0.20080
2008    0.20331
2009    0.23455
2010        NaN
2011    0.36146
2012        NaN
2013    0.44164
2014    0.47988
2015    0.61609
2016    0.77817
2017    1.00179
2018        NaN
Name: ค่าใช้จ่ายในการวิจัยและพัฒนา (คิดเป็น % ของจีดีพี), dtype: float64

In [97]:
ex6.interpolate(method='linear', limit_direction='forward', axis=0)

Year
1995         NaN
1996    0.119180
1997    0.102140
1998    0.175250
1999    0.248360
2000    0.244710
2001    0.252310
2002    0.230550
2003    0.245340
2004    0.238280
2005    0.218890
2006    0.232710
2007    0.200800
2008    0.203310
2009    0.234550
2010    0.298005
2011    0.361460
2012    0.401550
2013    0.441640
2014    0.479880
2015    0.616090
2016    0.778170
2017    1.001790
2018    1.001790
Name: ค่าใช้จ่ายในการวิจัยและพัฒนา (คิดเป็น % ของจีดีพี), dtype: float64

In [98]:
ex6.interpolate(method='linear', limit_direction='backward', axis=0)

Year
1995    0.119180
1996    0.119180
1997    0.102140
1998    0.175250
1999    0.248360
2000    0.244710
2001    0.252310
2002    0.230550
2003    0.245340
2004    0.238280
2005    0.218890
2006    0.232710
2007    0.200800
2008    0.203310
2009    0.234550
2010    0.298005
2011    0.361460
2012    0.401550
2013    0.441640
2014    0.479880
2015    0.616090
2016    0.778170
2017    1.001790
2018         NaN
Name: ค่าใช้จ่ายในการวิจัยและพัฒนา (คิดเป็น % ของจีดีพี), dtype: float64