In [63]:
#! -*- coding: UTF8 -*-
import os
os.chdir(os.getcwd())

## Import Module

In [64]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [65]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

## Import Data 

In [66]:
df1 = pd.read_excel('process_data/GPP_6210501001.xlsx',sheet_name="Ayutthaya",index_col="Year") #ตัวอย่าง
df1.head()

Agriculture, forestry and fishing  Mining and quarrying  Manufacturing  \
Year                                                                           
1995                               3069                   471          70294   
1996                               3305                   513          80942   
1997                               4056                   474          86917   
1998                               4805                   395          84878   
1999                               4030                   302          92332   

      Electricity, gas, steam and air conditioning supply  \
Year                                                        
1995                                               2030     
1996                                               2290     
1997                                               2697     
1998                                               3388     
1999                                               2974     

      Water supply; sewerage, waste management and remediation activities  \
Year                                                                        
1995                                                254                     
1996                                                324                     
1997                                                382                     
1998                                                420                     
1999                                                503                     

      Construction  Wholesale and retail trade and repair of motor vehicles  \
Year                                                                          
1995          1566                                              16137         
1996          5205                                              19161         
1997          1756                                              20641         
1998          1166                                              22362         
1999          1397                                              22431         

      Transportation and storage  Accommodation and food service activities  \
Year                                                                          
1995                        1392                                        655   
1996                        1626                                        819   
1997                        2219                                        675   
1998                        2306                                        666   
1999                        2483                                        685   

      Information and communication  ...  \
Year                                 ...   
1995                            472  ...   
1996                            595  ...   
1997                            575  ...   
1998                            585  ...   
1999                            836  ...   

      การนำเข้าสินค้าและบริการ (คิดเป็น % ของจีดีพี)  \
Year                                                   
1995                                       48.223830   
1996                                       45.255728   
1997                                       46.814732   
1998                                       42.303171   
1999                                       44.267746   

      มูลค่าเพิ่มของอุตสาหกรรม (คิดเป็น % ของจีดีพี)  \
Year                                                   
1995                                       37.278020   
1996                                       37.081286   
1997                                       36.564600   
1998                                       36.111727   
1999                                       36.378900   

      จำนวนประชากรทั้งหมด (คน)  \
Year                             
1995                  59467272   
1996                  60130190   
1997                  60846588   
1998                  61585103   
1999                  62298569   

      ค่าใช้จ่ายในการวิจัยและพัฒนา 

In [67]:
df1.keys()

Index(['Agriculture, forestry and fishing', 'Mining and quarrying',
       'Manufacturing', 'Electricity, gas, steam and air conditioning supply',
       'Water supply; sewerage, waste management and remediation activities',
       'Construction',
       'Wholesale and retail trade and repair of motor vehicles',
       'Transportation and storage',
       'Accommodation and food service activities',
       'Information and communication', 'Financial and insurance activities',
       'Real estate activities',
       'Professional, scientific and technical activities',
       'Administrative and support service activities',
       'Public administration and defence; compulsory social security',
       'Education', 'Human health activities',
       'Arts, entertainment and recreation', 'Other service activities',
       'การค้าสินค้า (คิดเป็น % ของจีดีพี)',
       'มูลค่าเพิ่มของการเกษตร (คิดเป็น % ของจีดีพี)',
       'การนำเข้าสินค้าและบริการ (คิดเป็น % ของจีดีพี)',
       'มูลค่าเพิ่มขอ

## Find data by Regression

##### รายจ่ายของประชากรในจังหวัดพระนครศรีอยุธยา (บาท)

In [68]:
ex1 = df1.loc[[i for i in range(2006,2019)],['รายจ่ายของประชากรในจังหวัดพระนครศรีอยุธยา (บาท)','GPP Per capita (Baht)']]
ex1

รายจ่ายของประชากรในจังหวัดพระนครศรีอยุธยา (บาท)  GPP Per capita (Baht)
Year                                                                        
2006                                         15859.00             298954.253
2007                                         16757.00             339993.396
2008                                         19201.00             438555.445
2009                                         20717.00             379657.777
2010                                         18789.00             427733.436
2011                                         17534.30             365800.945
2012                                         25215.89             378620.537
2013                                         20493.70             461789.496
2014                                         20409.63             417614.341
2015                                         22218.10             468325.834
2016                                         23095.32             444803.565
2017                                         23780.19             449602.967
2018                                         22790.08             454952.541

In [69]:
import statsmodels.api as sm
X = ex1[['GPP Per capita (Baht)']]
X = sm.add_constant(X, prepend=False)
X.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
2006             298954.253    1.0
2007             339993.396    1.0
2008             438555.445    1.0
2009             379657.777    1.0
2010             427733.436    1.0

In [70]:
y = ex1['รายจ่ายของประชากรในจังหวัดพระนครศรีอยุธยา (บาท)']
y.head()

Year
2006    15859.0
2007    16757.0
2008    19201.0
2009    20717.0
2010    18789.0
Name: รายจ่ายของประชากรในจังหวัดพระนครศรีอยุธยา (บาท), dtype: float64

In [71]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05,random_state=14)  

In [72]:
lm = LinearRegression()
lm.fit(X_train, y_train)

LinearRegression()

In [73]:
X_train

GPP Per capita (Baht)  const
Year                              
2009             379657.777    1.0
2018             454952.541    1.0
2007             339993.396    1.0
2006             298954.253    1.0
2015             468325.834    1.0
2010             427733.436    1.0
2008             438555.445    1.0
2016             444803.565    1.0
2013             461789.496    1.0
2012             378620.537    1.0
2014             417614.341    1.0
2017             449602.967    1.0

In [74]:
test_ex1 = df1.loc[[i for i in range(1995,2006)],['GPP Per capita (Baht)']]
test_ex1

GPP Per capita (Baht)
Year                       
1995             143862.554
1996             171503.917
1997             179223.451
1998             180611.806
1999             189856.706
2000             219141.847
2001             219060.592
2002             231122.492
2003             256743.101
2004             271765.117
2005             273739.910

In [75]:
X_test_ex1 = test_ex1[['GPP Per capita (Baht)']]
X_test_ex1 = sm.add_constant(X_test_ex1, prepend=False)
X_test_ex1.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
1995             143862.554    1.0
1996             171503.917    1.0
1997             179223.451    1.0
1998             180611.806    1.0
1999             189856.706    1.0

In [76]:
predictions = lm.predict(X_test_ex1)
predictions                   

array([12393.62893434, 13253.42143668, 13493.53974975, 13536.72492914,
       13824.29018795, 14735.21287514, 14732.68541513, 15107.87426468,
       15904.81063585, 16372.07474026, 16433.50124137])

##### เนื้อที่ที่ถือครองเพื่อการเกษตร (ไร่)

In [77]:
ex2 = df1.loc[[i for i in range(2010,2019)],['เนื้อที่ที่ถือครองเพื่อการเกษตร (ไร่)','GPP Per capita (Baht)']]
ex2

เนื้อที่ที่ถือครองเพื่อการเกษตร (ไร่)  GPP Per capita (Baht)
Year                                                              
2010                              1155861.0             427733.436
2011                              1158113.0             365800.945
2012                              1180726.0             378620.537
2013                              1177369.0             461789.496
2014                              1178443.0             417614.341
2015                              1177896.0             468325.834
2016                              1178345.0             444803.565
2017                              1178698.0             449602.967
2018                              1178475.0             454952.541

In [78]:
X = ex2[['GPP Per capita (Baht)']]
X = sm.add_constant(X, prepend=False)
X.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
2010             427733.436    1.0
2011             365800.945    1.0
2012             378620.537    1.0
2013             461789.496    1.0
2014             417614.341    1.0

In [79]:
y = ex2['เนื้อที่ที่ถือครองเพื่อการเกษตร (ไร่)']
y.head()

Year
2010    1155861.0
2011    1158113.0
2012    1180726.0
2013    1177369.0
2014    1178443.0
Name: เนื้อที่ที่ถือครองเพื่อการเกษตร (ไร่), dtype: float64

In [80]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05,random_state=14)  

In [81]:
lm = LinearRegression()
lm.fit(X_train, y_train)

LinearRegression()

In [82]:
test_ex2 = df1.loc[[i for i in range(1995,2010)],['GPP Per capita (Baht)']]
test_ex2

GPP Per capita (Baht)
Year                       
1995             143862.554
1996             171503.917
1997             179223.451
1998             180611.806
1999             189856.706
2000             219141.847
2001             219060.592
2002             231122.492
2003             256743.101
2004             271765.117
2005             273739.910
2006             298954.253
2007             339993.396
2008             438555.445
2009             379657.777

In [83]:
X_test_ex2 = test_ex2[['GPP Per capita (Baht)']]
X_test_ex2 = sm.add_constant(X_test_ex2, prepend=False)
X_test_ex2.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
1995             143862.554    1.0
1996             171503.917    1.0
1997             179223.451    1.0
1998             180611.806    1.0
1999             189856.706    1.0

In [84]:
predictions = lm.predict(X_test_ex2)
predictions  

array([1141681.33738848, 1144784.26279459, 1145650.83142842,
       1145806.68343912, 1146844.48447256, 1150131.9348067 ,
       1150122.81339674, 1151476.84126997, 1154352.92370433,
       1156039.24413279, 1156260.92767899, 1159091.40407385,
       1163698.31869885, 1174762.55912436, 1168150.90721711])

##### จำนวนโรงงานอุตสาหกรรม (โรงงาน)

In [85]:
ex3= df1.loc[[i for i in range(2011,2019)],['จำนวนโรงงานอุตสาหกรรม (โรงงาน)','GPP Per capita (Baht)']]
ex3

จำนวนโรงงานอุตสาหกรรม (โรงงาน)  GPP Per capita (Baht)
Year                                                       
2011                           147.0             365800.945
2012                           109.0             378620.537
2013                            93.0             461789.496
2014                           117.0             417614.341
2015                           132.0             468325.834
2016                           121.0             444803.565
2017                           117.0             449602.967
2018                            96.0             454952.541

In [86]:
X = ex3[['GPP Per capita (Baht)']]
X = sm.add_constant(X, prepend=False)
X.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
2011             365800.945    1.0
2012             378620.537    1.0
2013             461789.496    1.0
2014             417614.341    1.0
2015             468325.834    1.0

In [87]:
y = ex3['จำนวนโรงงานอุตสาหกรรม (โรงงาน)']
y.head()

Year
2011    147.0
2012    109.0
2013     93.0
2014    117.0
2015    132.0
Name: จำนวนโรงงานอุตสาหกรรม (โรงงาน), dtype: float64

In [88]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05,random_state=14)  

In [89]:
lm = LinearRegression()
lm.fit(X_train, y_train)

LinearRegression()

In [90]:
test_ex3 = df1.loc[[i for i in range(1995,2011)],['GPP Per capita (Baht)']]
test_ex3

GPP Per capita (Baht)
Year                       
1995             143862.554
1996             171503.917
1997             179223.451
1998             180611.806
1999             189856.706
2000             219141.847
2001             219060.592
2002             231122.492
2003             256743.101
2004             271765.117
2005             273739.910
2006             298954.253
2007             339993.396
2008             438555.445
2009             379657.777
2010             427733.436

In [91]:
X_test_ex3 = test_ex3[['GPP Per capita (Baht)']]
X_test_ex3 = sm.add_constant(X_test_ex3, prepend=False)
X_test_ex3.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
1995             143862.554    1.0
1996             171503.917    1.0
1997             179223.451    1.0
1998             180611.806    1.0
1999             189856.706    1.0

In [92]:
predictions = lm.predict(X_test_ex3)
predictions  

array([177.28011573, 171.30690907, 169.63874343, 169.33872453,
       167.34093237, 161.01251075, 161.03006969, 158.42353319,
       152.88700475, 149.64079703, 149.21405083, 143.76531512,
       134.89689274, 113.59796158, 126.32555185, 115.93656175])

##### สวนผักและไม้ดอก (ไร่)

In [93]:
ex4 = df1.loc[[i for i in range(2010,2019)],['เนื้อที่สวนผักและไม้ดอก (ไร่)','GPP Per capita (Baht)']]
ex4

เนื้อที่สวนผักและไม้ดอก (ไร่)  GPP Per capita (Baht)
Year                                                      
2010                    9042.000000             427733.436
2011                    9461.000000             365800.945
2012                    9598.000000             378620.537
2013                    9573.830465             461789.496
2014                    9510.000000             417614.341
2015                    9500.000000             468325.834
2016                    9711.000000             444803.565
2017                    9720.000000             449602.967
2018                    9713.000000             454952.541

In [94]:
X = ex4[['GPP Per capita (Baht)']]
X = sm.add_constant(X, prepend=False)
X.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
2010             427733.436    1.0
2011             365800.945    1.0
2012             378620.537    1.0
2013             461789.496    1.0
2014             417614.341    1.0

In [95]:
y = ex4['เนื้อที่สวนผักและไม้ดอก (ไร่)']
y.head()

Year
2010    9042.000000
2011    9461.000000
2012    9598.000000
2013    9573.830465
2014    9510.000000
Name: เนื้อที่สวนผักและไม้ดอก (ไร่), dtype: float64

In [96]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.01,random_state=14)

In [97]:
lm = LinearRegression()
lm.fit(X_train, y_train)

LinearRegression()

In [98]:
test_ex4 = df1.loc[[i for i in range(1995,2010)],['GPP Per capita (Baht)']]
test_ex4

GPP Per capita (Baht)
Year                       
1995             143862.554
1996             171503.917
1997             179223.451
1998             180611.806
1999             189856.706
2000             219141.847
2001             219060.592
2002             231122.492
2003             256743.101
2004             271765.117
2005             273739.910
2006             298954.253
2007             339993.396
2008             438555.445
2009             379657.777

In [99]:
X_test_ex4 = test_ex4[['GPP Per capita (Baht)']]
X_test_ex4 = sm.add_constant(X_test_ex4, prepend=False)
X_test_ex4.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
1995             143862.554    1.0
1996             171503.917    1.0
1997             179223.451    1.0
1998             180611.806    1.0
1999             189856.706    1.0

In [100]:
predictions = lm.predict(X_test_ex4)
predictions  

array([9067.81141342, 9114.3264205 , 9127.31688622, 9129.65321611,
       9145.21057444, 9194.49173835, 9194.35500208, 9214.65282039,
       9257.76729375, 9283.04640826, 9286.3695986 , 9328.80040575,
       9397.86125586, 9563.72190486, 9464.60865044])

##### เนื้อที่สำหรับปลูกนาข้าว (ไร่)

In [101]:
ex5 = df1.loc[[i for i in range(2010,2019)],['เนื้อที่สำหรับปลูกนาข้าว (ไร่)','GPP Per capita (Baht)']]
ex5

เนื้อที่สำหรับปลูกนาข้าว (ไร่)  GPP Per capita (Baht)
Year                                                       
2010                    1.046128e+06             427733.436
2011                    1.065030e+06             365800.945
2012                    1.065565e+06             378620.537
2013                    1.065336e+06             461789.496
2014                    1.065583e+06             417614.341
2015                    1.065016e+06             468325.834
2016                    1.065315e+06             444803.565
2017                    1.065376e+06             449602.967
2018                    1.065197e+06             454952.541

In [102]:
X = ex5[['GPP Per capita (Baht)']]
X = sm.add_constant(X, prepend=False)
X.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
2010             427733.436    1.0
2011             365800.945    1.0
2012             378620.537    1.0
2013             461789.496    1.0
2014             417614.341    1.0

In [103]:
y = ex5['เนื้อที่สำหรับปลูกนาข้าว (ไร่)']
y.head()

Year
2010    1.046128e+06
2011    1.065030e+06
2012    1.065565e+06
2013    1.065336e+06
2014    1.065583e+06
Name: เนื้อที่สำหรับปลูกนาข้าว (ไร่), dtype: float64

In [104]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.000000000001,random_state=14)

In [105]:
lm = LinearRegression()
lm.fit(X_train, y_train)

LinearRegression()

In [106]:
test_ex5 = df1.loc[[i for i in range(1995,2010)],['GPP Per capita (Baht)']]
test_ex5

GPP Per capita (Baht)
Year                       
1995             143862.554
1996             171503.917
1997             179223.451
1998             180611.806
1999             189856.706
2000             219141.847
2001             219060.592
2002             231122.492
2003             256743.101
2004             271765.117
2005             273739.910
2006             298954.253
2007             339993.396
2008             438555.445
2009             379657.777

In [107]:
X_test_ex5 = test_ex5[['GPP Per capita (Baht)']]
X_test_ex5 = sm.add_constant(X_test_ex5, prepend=False)
X_test_ex5.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
1995             143862.554    1.0
1996             171503.917    1.0
1997             179223.451    1.0
1998             180611.806    1.0
1999             189856.706    1.0

In [108]:
predictions = lm.predict(X_test_ex5)
predictions  

array([1064454.46045036, 1064305.74040025, 1064264.20664943,
       1064256.73682151, 1064206.99607641, 1064049.43193469,
       1064049.86911457, 1063984.97193955, 1063847.12424173,
       1063766.30062343, 1063755.67555715, 1063620.01371029,
       1063399.20899081, 1062868.9112314 , 1063185.80096423])

## Find data by Interpolation

In [111]:
ex6 = df1['ค่าใช้จ่ายในการวิจัยและพัฒนา (คิดเป็น % ของจีดีพี)']
ex6

Year
1995        NaN
1996    0.11918
1997    0.10214
1998        NaN
1999    0.24836
2000    0.24471
2001    0.25231
2002    0.23055
2003    0.24534
2004    0.23828
2005    0.21889
2006    0.23271
2007    0.20080
2008    0.20331
2009    0.23455
2010        NaN
2011    0.36146
2012        NaN
2013    0.44164
2014    0.47988
2015    0.61609
2016    0.77817
2017    1.00179
2018        NaN
Name: ค่าใช้จ่ายในการวิจัยและพัฒนา (คิดเป็น % ของจีดีพี), dtype: float64

In [112]:
ex6.interpolate(method='linear', limit_direction='forward', axis=0)

Year
1995         NaN
1996    0.119180
1997    0.102140
1998    0.175250
1999    0.248360
2000    0.244710
2001    0.252310
2002    0.230550
2003    0.245340
2004    0.238280
2005    0.218890
2006    0.232710
2007    0.200800
2008    0.203310
2009    0.234550
2010    0.298005
2011    0.361460
2012    0.401550
2013    0.441640
2014    0.479880
2015    0.616090
2016    0.778170
2017    1.001790
2018    1.001790
Name: ค่าใช้จ่ายในการวิจัยและพัฒนา (คิดเป็น % ของจีดีพี), dtype: float64

In [113]:
ex6.interpolate(method='linear', limit_direction='backward', axis=0)

Year
1995    0.119180
1996    0.119180
1997    0.102140
1998    0.175250
1999    0.248360
2000    0.244710
2001    0.252310
2002    0.230550
2003    0.245340
2004    0.238280
2005    0.218890
2006    0.232710
2007    0.200800
2008    0.203310
2009    0.234550
2010    0.298005
2011    0.361460
2012    0.401550
2013    0.441640
2014    0.479880
2015    0.616090
2016    0.778170
2017    1.001790
2018         NaN
Name: ค่าใช้จ่ายในการวิจัยและพัฒนา (คิดเป็น % ของจีดีพี), dtype: float64