In [222]:
import os
os.chdir(os.getcwd())

In [223]:
import pandas as pd
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix
%matplotlib inline

In [224]:
df = pd.read_csv("cancer.csv")
df.head()

Age  NumPregnancies  Smokes  YrOfSmokes  SmokesPacks  Contraceptives  \
0   18               1       0         0.0          0.0               0   
1   15               1       0         0.0          0.0               0   
2   34               1       0         0.0          0.0               0   
3   52               4       1        37.0         37.0               1   
4   46               4       0         0.0          0.0               1   

   YrOfContraceptives  Biopsy  
0                 0.0       0  
1                 0.0       0  
2                 0.0       0  
3                 3.0       0  
4                15.0       0

In [225]:
df[df['Biopsy'] == 1]

Age  NumPregnancies  Smokes  YrOfSmokes  SmokesPacks  Contraceptives  \
6     51               6       1        34.0         3.40               0   
19    40               1       0         0.0         0.00               1   
20    40               2       0         0.0         0.00               1   
38    37               3       1        12.0         6.00               1   
57    38               4       0         0.0         0.00               1   
82    33               2       0         0.0         0.00               1   
87    28               2       0         0.0         0.00               1   
89    25               2       0         0.0         0.00               1   
96    30               3       0         0.0         0.00               1   
98    29               3       1        10.0         2.00               1   
114   22               1       0         0.0         0.00               0   
120   22               2       1         5.0         1.25               1   

     YrOfContraceptives  Biopsy  
6                  0.00       1  
19                 0.25       1  
20                15.00       1  
38                13.00       1  
57                16.00       1  
82                 0.50       1  
87                 0.42       1  
89                 0.08       1  
96                 4.00       1  
98                 6.00       1  
114                0.00       1  
120                6.00       1

In [226]:
df.columns

Index(['Age', 'NumPregnancies', 'Smokes', 'YrOfSmokes', 'SmokesPacks',
       'Contraceptives', 'YrOfContraceptives', 'Biopsy'],
      dtype='object')

# Linear Regression: Affected Factors on Biopsy

In [227]:
import statsmodels.api as sm
import math
import numpy as np
X = df[['Age', 'NumPregnancies', 'Smokes', 'YrOfSmokes', 'SmokesPacks',
       'Contraceptives', 'YrOfContraceptives']]
X = sm.add_constant(X, prepend=False)
model = sm.OLS(df.Biopsy, X)
results = model.fit()
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                 Biopsy   R-squared:                       0.105
Model:                            OLS   Adj. R-squared:                  0.060
Method:                 Least Squares   F-statistic:                     2.328
Date:                Thu, 27 Jan 2022   Prob (F-statistic):             0.0282
Time:                        17:37:33   Log-Likelihood:                -10.020
No. Observations:                 147   AIC:                             36.04
Df Residuals:                     139   BIC:                             59.96
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Age                    0.0023      0

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


In [228]:
X

Age  NumPregnancies  Smokes  YrOfSmokes  SmokesPacks  Contraceptives  \
0     18               1       0         0.0          0.0               0   
1     15               1       0         0.0          0.0               0   
2     34               1       0         0.0          0.0               0   
3     52               4       1        37.0         37.0               1   
4     46               4       0         0.0          0.0               1   
..   ...             ...     ...         ...          ...             ...   
142   21               1       0         0.0          0.0               0   
143   23               2       0         0.0          0.0               0   
144   23               1       0         0.0          0.0               1   
145   24               1       0         0.0          0.0               0   
146   24               3       0         0.0          0.0               1   

     YrOfContraceptives  const  
0                  0.00    1.0  
1                  0.00    1.0  
2                  0.00    1.0  
3                  3.00    1.0  
4                 15.00    1.0  
..                  ...    ...  
142                0.00    1.0  
143                0.00    1.0  
144                7.00    1.0  
145                0.00    1.0  
146                0.25    1.0  

[147 rows x 8 columns]

# Linear Regression: Predicted Biopsy

In [229]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

In [230]:
import statsmodels.api as sm
X = df[['Age', 'NumPregnancies', 'Smokes', 'YrOfSmokes', 'SmokesPacks',
       'Contraceptives', 'YrOfContraceptives']]
X = sm.add_constant(X, prepend=False)
X.head()


/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


Age  NumPregnancies  Smokes  YrOfSmokes  SmokesPacks  Contraceptives  \
0   18               1       0         0.0          0.0               0   
1   15               1       0         0.0          0.0               0   
2   34               1       0         0.0          0.0               0   
3   52               4       1        37.0         37.0               1   
4   46               4       0         0.0          0.0               1   

   YrOfContraceptives  const  
0                 0.0    1.0  
1                 0.0    1.0  
2                 0.0    1.0  
3                 3.0    1.0  
4                15.0    1.0

In [231]:
y = df['Biopsy']
y.head()


0    0
1    0
2    0
3    0
4    0
Name: Biopsy, dtype: int64

In [232]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.05, random_state=14)


In [233]:
lm = LinearRegression()
lm.fit(X_train, y_train)


LinearRegression()

In [234]:
lm.coef_


array([ 0.00242484, -0.02923072, -0.04102187,  0.02713017, -0.02661242,
        0.06045781,  0.00547888,  0.        ])

In [235]:
lm.intercept_


0.004683733784360544

In [236]:
predictions = lm.predict(X_train)
predictions


array([ 7.21102144e-02,  3.12342667e-02,  4.07912141e-02,  1.02426038e-01,
        9.09328334e-02,  4.35351764e-02,  1.40271028e-01,  8.21461533e-02,
        7.68768679e-02,  2.52763988e-02,  4.80657462e-02,  1.85857014e-01,
        5.14530855e-02,  8.72884669e-02,  8.36052464e-02, -1.76702238e-02,
        5.78977127e-02,  1.12927874e-01,  4.31897101e-02,  1.80439840e-01,
        1.25011413e-01,  9.52328687e-02,  3.63932659e-01,  7.43888165e-01,
        1.85857014e-01,  6.27474008e-02,  7.52049281e-02,  5.20822737e-02,
        9.69702367e-02,  8.91336784e-02,  6.50583674e-02,  1.99370917e-03,
        3.36492722e-02,  7.82377127e-02,  1.56481249e-01,  9.70285246e-02,
        1.08748056e-01, -1.76702238e-02, -3.23518784e-02,  2.63259679e-01,
       -4.31134884e-04, -2.73696000e-02,  1.26999774e-01,  4.96574296e-02,
        2.62421497e-02,  9.26824134e-03,  2.62421497e-02,  3.70153638e-02,
        4.82664629e-02,  1.48174749e-01,  6.86709267e-02,  4.25488704e-01,
        2.87995841e-02,  

In [237]:
metrics.mean_squared_error(y_train,predictions)

0.07048754663534476

In [238]:
metrics.r2_score(y_train,predictions)

0.10637146421161658

In [239]:
Age = 22
NumPregnancies = 1
Smokes = 0
YrOfSmokes = 0
SmokesPacks = 0
Contraceptives = 0
YrOfContraceptives = 0
predicted_Biopsy = lm.coef_[0]*Age+lm.coef_[1] * NumPregnancies+lm.coef_[2]*Smokes + \
    lm.coef_[3]*YrOfSmokes + lm.coef_[4]*SmokesPacks + \
    lm.coef_[5]*Contraceptives+lm.coef_[6]*YrOfContraceptives+lm.intercept_
predicted_Biopsy


0.028799584056619233

# Logistic Regression, StatModel: Predicted Biopsy

In [240]:
from pandas.plotting import scatter_matrix


In [241]:
y = df['Biopsy']


In [242]:
import statsmodels.discrete.discrete_model as sd
model = sd.Logit(y, X)
result = model.fit()
result.summary()


Optimization terminated successfully.
         Current function value: 0.244745
         Iterations 8


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                 Biopsy   No. Observations:                  147
Model:                          Logit   Df Residuals:                      139
Method:                           MLE   Df Model:                            7
Date:                Thu, 27 Jan 2022   Pseudo R-squ.:                  0.1344
Time:                        17:37:34   Log-Likelihood:                -35.978
converged:                       True   LL-Null:                       -41.563
Covariance Type:            nonrobust   LLR p-value:                    0.1314
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
Age                    0.0363      0.058      0.622      0.534      -0.078       0.151
NumPregnancies        -0.4134      0.325     -1.272      0.203      -1.051       0.224
Smokes                -0.1606      1.287     -0.125      0.901      -2.683       2.362
YrOfSmokes             0.2089      0.105      1.986      0.047       0.003       0.415
SmokesPacks           -0.2106      0.126     -1.667      0.096      -0.458       0.037
Contraceptives         1.2708      1.108      1.146      0.252      -0.902       3.443
YrOfContraceptives     0.0574      0.069      0.830      0.406      -0.078       0.193
const                 -4.1121      1.976     -2.081      0.037      -7.984      -0.240
======================================================================================
"""

In [243]:
result.params


Age                   0.036349
NumPregnancies       -0.413397
Smokes               -0.160611
YrOfSmokes            0.208913
SmokesPacks          -0.210628
Contraceptives        1.270799
YrOfContraceptives    0.057368
const                -4.112076
dtype: float64

In [244]:
Age = 22
NumPregnancies = 1
Smokes = 0
YrOfSmokes = 0
SmokesPacks = 0
Contraceptives = 0
YrOfContraceptives = 0
y_Biopsy = math.e**(result.params.const+result.params.Age*Age +
             result.params.NumPregnancies*NumPregnancies+result.params.Smokes*Smokes+result.params.YrOfSmokes*YrOfSmokes+result.params.SmokesPacks+result.params.Contraceptives*Contraceptives + result.params.YrOfContraceptives*YrOfContraceptives)/(1+(math.e**(result.params.const+result.params.Age*Age +
                                                                                                                                                                                                                                                                   result.params.NumPregnancies*NumPregnancies+result.params.Smokes*Smokes+result.params.YrOfSmokes*YrOfSmokes+result.params.SmokesPacks+result.params.Contraceptives*Contraceptives + result.params.YrOfContraceptives*YrOfContraceptives)))
y_Biopsy


0.019144194604518775

# Logistic Regression, ScikitLearn: Predicted Biopsy

In [245]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix


In [246]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.05, random_state=14)


In [247]:
model = LogisticRegression()
model.fit(X_train, y_train)


LogisticRegression()

In [248]:
model.coef_


array([[ 2.70725671e-02, -3.67461745e-01,  2.77727873e-02,
         1.81871084e-01, -1.84760993e-01,  6.22137615e-01,
         7.18968890e-02, -9.44807292e-06]])

In [249]:
model.intercept_


array([-3.38671389])

In [250]:
# lecture example uses all data to train
# typically use X_test to do prediction

predictions = model.predict(X_train)
predictions


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0])

In [251]:
# lecture example uses all data to train
# typically use y_test to observe confusion matrix 

print(confusion_matrix(y_train,predictions))

[[127   0]
 [ 11   1]]


In [252]:
# lecture example uses all data to train
# typically use y_test to observe confusion matrix

print(classification_report(y_train, predictions))


              precision    recall  f1-score   support

           0       0.92      1.00      0.96       127
           1       1.00      0.08      0.15        12

    accuracy                           0.92       139
   macro avg       0.96      0.54      0.56       139
weighted avg       0.93      0.92      0.89       139



In [253]:
my_data = {'Age': [22],
           'NumPregnancies': [1],
           'Smokes': [0],
           'YrOfSmokes': [0],
           'SmokesPacks': [0],
           'Contraceptives': [0],
           'YrOfContraceptives': [0],
           'const': [1.0]
           }
my_df = pd.DataFrame(my_data, columns=['Age', 'NumPregnancies', 'Smokes', 'YrOfSmokes', 'SmokesPacks',
                                       'Contraceptives', 'YrOfContraceptives', 'const'])
my_df


Age  NumPregnancies  Smokes  YrOfSmokes  SmokesPacks  Contraceptives  \
0   22               1       0           0            0               0   

   YrOfContraceptives  const  
0                   0    1.0

In [254]:
predictions = model.predict(my_df)
predictions


array([0])