In [50]:
#! -*- coding: UTF8 -*-
import os
os.chdir(os.getcwd())

## Import Module

In [51]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [52]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

## Import Data 

In [53]:
df1 = pd.read_excel('process_data/GPP_6210501001.xlsx',sheet_name="SingBuri",index_col="Year") #ตัวอย่าง
df1.head()

Agriculture, forestry and fishing  Mining and quarrying  Manufacturing  \
Year                                                                           
1995                        1517.167364             42.410974    2247.735336   
1996                        2151.732729             39.837997    2525.526291   
1997                        2438.909192             28.967616    2434.777758   
1998                        2872.227679             23.722862    2635.233786   
1999                        1738.973389             18.169377    2775.669860   

      Electricity, gas, steam and air conditioning supply  \
Year                                                        
1995                                         251.360573     
1996                                         268.322033     
1997                                         282.656660     
1998                                         362.892721     
1999                                         310.675285     

      Water supply; sewerage, waste management and remediation activities  \
Year                                                                        
1995                                          20.751178                     
1996                                          21.818723                     
1997                                          23.104803                     
1998                                          23.570355                     
1999                                          26.850346                     

      Construction  Wholesale and retail trade and repair of motor vehicles  \
Year                                                                          
1995    540.088489                                        1553.350483         
1996    412.596415                                        1778.579003         
1997    399.625836                                        1934.577471         
1998    241.360017                                        1787.959114         
1999    240.759815                                        1607.285461         

      Transportation and storage  Accommodation and food service activities  \
Year                                                                          
1995                  662.278852                                  43.742963   
1996                  737.967580                                  37.939543   
1997                  790.819202                                  44.211324   
1998                  724.545611                                  45.740985   
1999                  736.278279                                  63.183246   

      Information and communication  ...  \
Year                                 ...   
1995                      80.752569  ...   
1996                      90.268175  ...   
1997                      89.376423  ...   
1998                      87.423898  ...   
1999                      98.627151  ...   

      การนำเข้าสินค้าและบริการ (คิดเป็น % ของจีดีพี)  \
Year                                                   
1995                                       48.223830   
1996                                       45.255728   
1997                                       46.814732   
1998                                       42.303171   
1999                                       44.267746   

      มูลค่าเพิ่มของอุตสาหกรรม (คิดเป็น % ของจีดีพี)  \
Year                                                   
1995                                       37.278020   
1996                                       37.081286   
1997                                       36.564600   
1998                                       36.111727   
1999                                       36.378900   

      จำนวนประชากรทั้งหมด (คน)  \
Year                             
1995                  59467272   
1996                  60130190   
1997                  60846588   
1998                  61585103   
1999                  62298569   

      ค่าใช้จ่ายในการวิจัยและพัฒนา 

In [54]:
df1.keys()

Index(['Agriculture, forestry and fishing', 'Mining and quarrying',
       'Manufacturing', 'Electricity, gas, steam and air conditioning supply',
       'Water supply; sewerage, waste management and remediation activities',
       'Construction',
       'Wholesale and retail trade and repair of motor vehicles',
       'Transportation and storage',
       'Accommodation and food service activities',
       'Information and communication', 'Financial and insurance activities',
       'Real estate activities',
       'Professional, scientific and technical activities',
       'Administrative and support service activities',
       'Public administration and defence; compulsory social security',
       'Education', 'Human health activities',
       'Arts, entertainment and recreation', 'Other service activities',
       'การค้าสินค้า (คิดเป็น % ของจีดีพี)',
       'มูลค่าเพิ่มของการเกษตร (คิดเป็น % ของจีดีพี)',
       'การนำเข้าสินค้าและบริการ (คิดเป็น % ของจีดีพี)',
       'มูลค่าเพิ่มขอ

## Find data by Regression

##### รายจ่ายของประชากรในจังหวัดสิงห์บุรี (บาท)

In [55]:
ex1 = df1.loc[[i for i in range(2006,2019)],['รายจ่ายของประชากรในจังหวัดสิงห์บุรี (บาท)','GPP Per capita (Baht)']]
ex1

รายจ่ายของประชากรในจังหวัดสิงห์บุรี (บาท)  GPP Per capita (Baht)
Year                                                                  
2006                                   16209.00             298954.253
2007                                   14988.00             339993.396
2008                                   13792.00             438555.445
2009                                   17787.00             379657.777
2010                                   15643.00             427733.436
2011                                   19207.10             365800.945
2012                                   23474.62             378620.537
2013                                   22118.20             461789.496
2014                                   19631.55             417614.341
2015                                   22136.80             468325.834
2016                                   19381.46             444803.565
2017                                   20262.78             449602.967
2018                                   19773.04             454952.541

In [56]:
import statsmodels.api as sm
X = ex1[['GPP Per capita (Baht)']]
X = sm.add_constant(X, prepend=False)
X.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
2006             298954.253    1.0
2007             339993.396    1.0
2008             438555.445    1.0
2009             379657.777    1.0
2010             427733.436    1.0

In [57]:
y = ex1['รายจ่ายของประชากรในจังหวัดสิงห์บุรี (บาท)']
y.head()

Year
2006    16209.0
2007    14988.0
2008    13792.0
2009    17787.0
2010    15643.0
Name: รายจ่ายของประชากรในจังหวัดสิงห์บุรี (บาท), dtype: float64

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05,random_state=14)  

In [59]:
lm = LinearRegression()
lm.fit(X_train, y_train)

LinearRegression()

In [60]:
X_train

GPP Per capita (Baht)  const
Year                              
2009             379657.777    1.0
2018             454952.541    1.0
2007             339993.396    1.0
2006             298954.253    1.0
2015             468325.834    1.0
2010             427733.436    1.0
2008             438555.445    1.0
2016             444803.565    1.0
2013             461789.496    1.0
2012             378620.537    1.0
2014             417614.341    1.0
2017             449602.967    1.0

In [61]:
test_ex1 = df1.loc[[i for i in range(1995,2006)],['GPP Per capita (Baht)']]
test_ex1

GPP Per capita (Baht)
Year                       
1995             143862.554
1996             171503.917
1997             179223.451
1998             180611.806
1999             189856.706
2000             219141.847
2001             219060.592
2002             231122.492
2003             256743.101
2004             271765.117
2005             273739.910

In [62]:
X_test_ex1 = test_ex1[['GPP Per capita (Baht)']]
X_test_ex1 = sm.add_constant(X_test_ex1, prepend=False)
X_test_ex1.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
1995             143862.554    1.0
1996             171503.917    1.0
1997             179223.451    1.0
1998             180611.806    1.0
1999             189856.706    1.0

In [63]:
predictions = lm.predict(X_test_ex1)
predictions                   

array([12384.87013329, 13039.34837251, 13222.1276016 , 13255.00037042,
       13473.89644562, 14167.29523052, 14165.37131564, 14450.96689477,
       15057.59874089, 15413.28245234, 15460.04060408])

##### เนื้อที่ที่ถือครองเพื่อการเกษตร (ไร่)

In [64]:
ex2 = df1.loc[[i for i in range(2010,2019)],['เนื้อที่ที่ถือครองเพื่อการเกษตร (ไร่)','GPP Per capita (Baht)']]
ex2

เนื้อที่ที่ถือครองเพื่อการเกษตร (ไร่)  GPP Per capita (Baht)
Year                                                              
2010                               449686.0             427733.436
2011                               449681.0             365800.945
2012                               492314.0             378620.537
2013                               491212.0             461789.496
2014                               491553.0             417614.341
2015                               491350.0             468325.834
2016                               491322.0             444803.565
2017                               491855.0             449602.967
2018                               492113.0             454952.541

In [65]:
X = ex2[['GPP Per capita (Baht)']]
X = sm.add_constant(X, prepend=False)
X.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
2010             427733.436    1.0
2011             365800.945    1.0
2012             378620.537    1.0
2013             461789.496    1.0
2014             417614.341    1.0

In [66]:
y = ex2['เนื้อที่ที่ถือครองเพื่อการเกษตร (ไร่)']
y.head()

Year
2010    449686.0
2011    449681.0
2012    492314.0
2013    491212.0
2014    491553.0
Name: เนื้อที่ที่ถือครองเพื่อการเกษตร (ไร่), dtype: float64

In [67]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05,random_state=14)  

In [68]:
lm = LinearRegression()
lm.fit(X_train, y_train)

LinearRegression()

In [69]:
test_ex2 = df1.loc[[i for i in range(1995,2010)],['GPP Per capita (Baht)']]
test_ex2

GPP Per capita (Baht)
Year                       
1995             143862.554
1996             171503.917
1997             179223.451
1998             180611.806
1999             189856.706
2000             219141.847
2001             219060.592
2002             231122.492
2003             256743.101
2004             271765.117
2005             273739.910
2006             298954.253
2007             339993.396
2008             438555.445
2009             379657.777

In [70]:
X_test_ex2 = test_ex2[['GPP Per capita (Baht)']]
X_test_ex2 = sm.add_constant(X_test_ex2, prepend=False)
X_test_ex2.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
1995             143862.554    1.0
1996             171503.917    1.0
1997             179223.451    1.0
1998             180611.806    1.0
1999             189856.706    1.0

In [71]:
predictions = lm.predict(X_test_ex2)
predictions  

array([407634.68248071, 414866.32629839, 416885.94162367, 417249.16860536,
       419667.85627753, 427329.55186261, 427308.29360489, 430463.97607122,
       437166.94215433, 441097.06199449, 441613.71522862, 448210.39237775,
       458947.21692431, 484733.41394755, 469324.37074414])

##### จำนวนโรงงานอุตสาหกรรม (โรงงาน)

In [72]:
ex3= df1.loc[[i for i in range(2011,2019)],['จำนวนโรงงานอุตสาหกรรม (โรงงาน)','GPP Per capita (Baht)']]
ex3

จำนวนโรงงานอุตสาหกรรม (โรงงาน)  GPP Per capita (Baht)
Year                                                       
2011                             9.0             365800.945
2012                             6.0             378620.537
2013                             8.0             461789.496
2014                             4.0             417614.341
2015                             6.0             468325.834
2016                            11.0             444803.565
2017                             6.0             449602.967
2018                             5.0             454952.541

In [73]:
X = ex3[['GPP Per capita (Baht)']]
X = sm.add_constant(X, prepend=False)
X.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
2011             365800.945    1.0
2012             378620.537    1.0
2013             461789.496    1.0
2014             417614.341    1.0
2015             468325.834    1.0

In [74]:
y = ex3['จำนวนโรงงานอุตสาหกรรม (โรงงาน)']
y.head()

Year
2011    9.0
2012    6.0
2013    8.0
2014    4.0
2015    6.0
Name: จำนวนโรงงานอุตสาหกรรม (โรงงาน), dtype: float64

In [75]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05,random_state=14)  

In [76]:
lm = LinearRegression()
lm.fit(X_train, y_train)

LinearRegression()

In [77]:
test_ex3 = df1.loc[[i for i in range(1995,2011)],['GPP Per capita (Baht)']]
test_ex3

GPP Per capita (Baht)
Year                       
1995             143862.554
1996             171503.917
1997             179223.451
1998             180611.806
1999             189856.706
2000             219141.847
2001             219060.592
2002             231122.492
2003             256743.101
2004             271765.117
2005             273739.910
2006             298954.253
2007             339993.396
2008             438555.445
2009             379657.777
2010             427733.436

In [78]:
X_test_ex3 = test_ex3[['GPP Per capita (Baht)']]
X_test_ex3 = sm.add_constant(X_test_ex3, prepend=False)
X_test_ex3.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
1995             143862.554    1.0
1996             171503.917    1.0
1997             179223.451    1.0
1998             180611.806    1.0
1999             189856.706    1.0

In [79]:
predictions = lm.predict(X_test_ex3)
predictions  

array([9.72097777, 9.38690832, 9.29361116, 9.27683171, 9.16509921,
       8.8111633 , 8.81214533, 8.66636699, 8.35672007, 8.1751662 ,
       8.15129914, 7.8465623 , 7.35056925, 6.15936282, 6.87119137,
       6.29015602])

##### เนื้อที่สวนผักและไม้ดอก (ไร่)

In [80]:
ex4 = df1.loc[[i for i in range(2010,2019)],['เนื้อที่สวนผักและไม้ดอก (ไร่)','GPP Per capita (Baht)']]
ex4

เนื้อที่สวนผักและไม้ดอก (ไร่)  GPP Per capita (Baht)
Year                                                      
2010                    2268.000000             427733.436
2011                    2284.000000             365800.945
2012                    2261.000000             378620.537
2013                    2261.341851             461789.496
2014                    2241.000000             417614.341
2015                    2353.000000             468325.834
2016                    2348.000000             444803.565
2017                    2346.000000             449602.967
2018                    2344.000000             454952.541

In [81]:
X = ex4[['GPP Per capita (Baht)']]
X = sm.add_constant(X, prepend=False)
X.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
2010             427733.436    1.0
2011             365800.945    1.0
2012             378620.537    1.0
2013             461789.496    1.0
2014             417614.341    1.0

In [82]:
y = ex4['เนื้อที่สวนผักและไม้ดอก (ไร่)']
y.head()

Year
2010    2268.000000
2011    2284.000000
2012    2261.000000
2013    2261.341851
2014    2241.000000
Name: เนื้อที่สวนผักและไม้ดอก (ไร่), dtype: float64

In [83]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.01,random_state=14)

In [84]:
lm = LinearRegression()
lm.fit(X_train, y_train)

LinearRegression()

In [85]:
test_ex4 = df1.loc[[i for i in range(1995,2010)],['GPP Per capita (Baht)']]
test_ex4

GPP Per capita (Baht)
Year                       
1995             143862.554
1996             171503.917
1997             179223.451
1998             180611.806
1999             189856.706
2000             219141.847
2001             219060.592
2002             231122.492
2003             256743.101
2004             271765.117
2005             273739.910
2006             298954.253
2007             339993.396
2008             438555.445
2009             379657.777

In [86]:
X_test_ex4 = test_ex4[['GPP Per capita (Baht)']]
X_test_ex4 = sm.add_constant(X_test_ex4, prepend=False)
X_test_ex4.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
1995             143862.554    1.0
1996             171503.917    1.0
1997             179223.451    1.0
1998             180611.806    1.0
1999             189856.706    1.0

In [87]:
predictions = lm.predict(X_test_ex4)
predictions  

array([2134.56825574, 2150.25363505, 2154.63416501, 2155.42200152,
       2160.66811631, 2177.28627456, 2177.24016557, 2184.08481635,
       2198.62349776, 2207.14789719, 2208.26851404, 2222.57665558,
       2245.86474469, 2301.79480589, 2268.37271078])

##### เนื้อที่สำหรับปลูกนาข้าว (ไร่)

In [88]:
ex5 = df1.loc[[i for i in range(2010,2019)],['เนื้อที่สำหรับปลูกนาข้าว (ไร่)','GPP Per capita (Baht)']]
ex5

เนื้อที่สำหรับปลูกนาข้าว (ไร่)  GPP Per capita (Baht)
Year                                                       
2010                        313067.0             427733.436
2011                        344589.0             365800.945
2012                        345037.0             378620.537
2013                        345116.0             461789.496
2014                        345313.0             417614.341
2015                        345205.0             468325.834
2016                        345244.0             444803.565
2017                        345124.0             449602.967
2018                        345409.0             454952.541

In [89]:
X = ex5[['GPP Per capita (Baht)']]
X = sm.add_constant(X, prepend=False)
X.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
2010             427733.436    1.0
2011             365800.945    1.0
2012             378620.537    1.0
2013             461789.496    1.0
2014             417614.341    1.0

In [90]:
y = ex5['เนื้อที่สำหรับปลูกนาข้าว (ไร่)']
y.head()

Year
2010    313067.0
2011    344589.0
2012    345037.0
2013    345116.0
2014    345313.0
Name: เนื้อที่สำหรับปลูกนาข้าว (ไร่), dtype: float64

In [91]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.000000000001,random_state=14)

In [92]:
lm = LinearRegression()
lm.fit(X_train, y_train)

LinearRegression()

In [93]:
test_ex5 = df1.loc[[i for i in range(1995,2010)],['GPP Per capita (Baht)']]
test_ex5

GPP Per capita (Baht)
Year                       
1995             143862.554
1996             171503.917
1997             179223.451
1998             180611.806
1999             189856.706
2000             219141.847
2001             219060.592
2002             231122.492
2003             256743.101
2004             271765.117
2005             273739.910
2006             298954.253
2007             339993.396
2008             438555.445
2009             379657.777

In [94]:
X_test_ex5 = test_ex5[['GPP Per capita (Baht)']]
X_test_ex5 = sm.add_constant(X_test_ex5, prepend=False)
X_test_ex5.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


GPP Per capita (Baht)  const
Year                              
1995             143862.554    1.0
1996             171503.917    1.0
1997             179223.451    1.0
1998             180611.806    1.0
1999             189856.706    1.0

In [95]:
predictions = lm.predict(X_test_ex5)
predictions  

array([342336.26697967, 342215.98331415, 342182.39112676, 342176.34958574,
       342136.11964269, 342008.68294195, 342009.03652977, 341956.54817943,
       341845.05799122, 341779.68845254, 341771.09497831, 341661.37269003,
       341482.78748243, 341053.88661621, 341310.1846648 ])

## Find data by Interpolation

In [96]:
ex6 = df1['ค่าใช้จ่ายในการวิจัยและพัฒนา (คิดเป็น % ของจีดีพี)']
ex6

Year
1995        NaN
1996    0.11918
1997    0.10214
1998        NaN
1999    0.24836
2000    0.24471
2001    0.25231
2002    0.23055
2003    0.24534
2004    0.23828
2005    0.21889
2006    0.23271
2007    0.20080
2008    0.20331
2009    0.23455
2010        NaN
2011    0.36146
2012        NaN
2013    0.44164
2014    0.47988
2015    0.61609
2016    0.77817
2017    1.00179
2018        NaN
Name: ค่าใช้จ่ายในการวิจัยและพัฒนา (คิดเป็น % ของจีดีพี), dtype: float64

In [97]:
ex6.interpolate(method='linear', limit_direction='forward', axis=0)

Year
1995         NaN
1996    0.119180
1997    0.102140
1998    0.175250
1999    0.248360
2000    0.244710
2001    0.252310
2002    0.230550
2003    0.245340
2004    0.238280
2005    0.218890
2006    0.232710
2007    0.200800
2008    0.203310
2009    0.234550
2010    0.298005
2011    0.361460
2012    0.401550
2013    0.441640
2014    0.479880
2015    0.616090
2016    0.778170
2017    1.001790
2018    1.001790
Name: ค่าใช้จ่ายในการวิจัยและพัฒนา (คิดเป็น % ของจีดีพี), dtype: float64

In [98]:
ex6.interpolate(method='linear', limit_direction='backward', axis=0)

Year
1995    0.119180
1996    0.119180
1997    0.102140
1998    0.175250
1999    0.248360
2000    0.244710
2001    0.252310
2002    0.230550
2003    0.245340
2004    0.238280
2005    0.218890
2006    0.232710
2007    0.200800
2008    0.203310
2009    0.234550
2010    0.298005
2011    0.361460
2012    0.401550
2013    0.441640
2014    0.479880
2015    0.616090
2016    0.778170
2017    1.001790
2018         NaN
Name: ค่าใช้จ่ายในการวิจัยและพัฒนา (คิดเป็น % ของจีดีพี), dtype: float64